package com.trapedza.bankfusion.extensionpoints;


public enum NCCUploadFields
{
  CLEARINGCODE, IDENTIFIERCODE, SUBBRANCHSUFFIX, BANKSHORTNAME, BANKLONGNAME, BANKCODE, BRANCHNAME, ADDRESSLINE1, ADDRESSLINE2, ADDRESSLINE3, ADDRESSLINE4, ADDRESSLINE5, REVISIONDATE;
}