package com.trapedza.bankfusion.fatoms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.misys.bankfusion.common.exception.ExceptionUtil;
import com.trapedza.bankfusion.core.BankFusionException;
import com.trapedza.bankfusion.persistence.core.IPersistenceObjectsFactory;
import com.trapedza.bankfusion.servercommon.commands.BankFusionEnvironment;
import com.trapedza.bankfusion.servercommon.core.BankFusionThreadLocal;
import com.trapedza.bankfusion.steps.refimpl.AbstractPostingInsert;

public class PostingInsert extends AbstractPostingInsert {

    private IPersistenceObjectsFactory factory = BankFusionThreadLocal.getPersistanceFactory();
    private static final transient Log logger = LogFactory.getLog(PostingInsert.class.getName());

    public PostingInsert(BankFusionEnvironment env) {
        super(env);
    }

    private static final String INSERT_ACCOUNT = "INSERT INTO ACCOUNT ( "
            + " ACCOUNTID,PRODUCTID,ISOCURRENCYCODE,PSEUDONAME,ACCOUNTDESCRIPTION,ACCOUNTNAME,CLEAREDBALANCE,BOOKEDBALANCE,CHEQUEDEPOSITBALANCE,LASTINTERESTACCRUALDATE,CREDITLIMIT,DEBITLIMIT,JOINTACCOUNT,OPENDATE,OPENEDBYUSER, LASTSTATICAMENDMENTDATE,AMENDEDBYUSER,"
            + " LASTTRANSACTIONDATE,STOPPED,STOPPEDBYUSER,STOPDATE,STOPREASON,STOPCODE, CLOSED, CLOSUREDATE,DATEOFDORMANCY,DORMANTSTATUS,MINOPENINGBALANCEAMOUNT,LOWESTBALANCE, LOWESTBALANCEDATE,PASSBOOKINDICATOR,FEEWAIVEINDICATOR,LIMITEXCESSACTION,"
            + "LIMITINDICATOR,LIMITREF1,LIMITREF2,LIMITREF3,LIMITREF4,LIMITREF5,LIMITREVIEWDATE,LIMITEXPIRYDATE,LASTCREDITLIMITCHANGEDATE,LASTDEBITLIMITCHANGEDATE,TAXINDICATORCR,TAXINDICATORDR,PEROUTERPROFILEID,STANDINGORDER,"
            + "SERVICEFEE,TAXATION,VERSIONNUM,DORMANTREACTIVATIONDATE,BLOCKEDBALANCE,LASTINTHISTSTRIPDATE,LASTTRANSHISTSTRIPDATE,ACCOUNTTAKEONDATE,ACCRIGHTSINDICATOR,ACCOUNTSTYLE,CHARGEFUNDINGACCOUNTID,LASTCREDITTRANSDTTM,LASTDEBITTRANSDTTM,"
            + "TEMPACCOUNTLIMIT,TEMPLIMEXPIRYDATE,PRODUCTCONTEXTCODE,BRANCHSORTCODE,UBACCTRANSCOUNTER,UBACCOUNTSTATUS,UBISARCHIVE,UBISDELETE,UBCUSTOMERCODE,UBACCRIGHTSINDREASON,UBACCRIGHTSINDCHANGEDT,UBACCRIGHTSINDCHANGEDBY,UBINDUSTRYCODE,UBUNACCRUEDAMOUNT,UBSIGNIFICANTEXCESSAMOUNT,UBNOTICEFREEWITHDRAWALAMOUNT,UBFABAPPLICABLE, UBCOOLINGOFFENDDT)"
            + "VALUES('01210PER00101','savings','EUR','','Savings Account','001 P kumar',9999999.000000,9999999.000000,0.000000,'2011-09-20',0.000000,0.000000,'N','2011-08-14',NULL,'2011-08-14 18:48:07.000',NULL,'2013-08-30','N',"
            + "NULL,'1970-01-01',NULL,NULL,'N','1970-01-01','1970-01-01','N',0.000000,0.000000,'1970-01-01','N','N',0,0,'PER001','','','','','1970-01-01 05:30:00.000','1970-01-01 00:00:00.000','2011-08-14','2011-08-14',NULL,NULL,NULL,"
            + "NULL,0,0,3,'1970-01-01',0.000000,'2011-08-14 00:00:00.000','2011-08-14 00:00:00.000','2011-08-14 00:00:00.000',1,NULL,NULL,'2011-09-07 23:50:49.000','2013-08-30 12:40:46.504',0.000000,'1970-01-01 00:00:00.000',"
            + "'01210DEFAULTEUR',NULL,3,'002','N','N','PER001',NULL,'1970-01-01',NULL,NULL,0,0,0,'N', '1970-01-01')";

    private static final String INSERT_ACCOUNT1 = "INSERT INTO ACCOUNT ( "
            + " ACCOUNTID,PRODUCTID,ISOCURRENCYCODE,PSEUDONAME,ACCOUNTDESCRIPTION,ACCOUNTNAME,CLEAREDBALANCE,BOOKEDBALANCE,CHEQUEDEPOSITBALANCE,LASTINTERESTACCRUALDATE,CREDITLIMIT,DEBITLIMIT,JOINTACCOUNT,OPENDATE,OPENEDBYUSER, LASTSTATICAMENDMENTDATE,AMENDEDBYUSER,"
            + " LASTTRANSACTIONDATE,STOPPED,STOPPEDBYUSER,STOPDATE,STOPREASON,STOPCODE, CLOSED, CLOSUREDATE,DATEOFDORMANCY,DORMANTSTATUS,MINOPENINGBALANCEAMOUNT,LOWESTBALANCE, LOWESTBALANCEDATE,PASSBOOKINDICATOR,FEEWAIVEINDICATOR,LIMITEXCESSACTION,"
            + "LIMITINDICATOR,LIMITREF1,LIMITREF2,LIMITREF3,LIMITREF4,LIMITREF5,LIMITREVIEWDATE,LIMITEXPIRYDATE,LASTCREDITLIMITCHANGEDATE,LASTDEBITLIMITCHANGEDATE,TAXINDICATORCR,TAXINDICATORDR,PEROUTERPROFILEID,STANDINGORDER,"
            + "SERVICEFEE,TAXATION,VERSIONNUM,DORMANTREACTIVATIONDATE,BLOCKEDBALANCE,LASTINTHISTSTRIPDATE,LASTTRANSHISTSTRIPDATE,ACCOUNTTAKEONDATE,ACCRIGHTSINDICATOR,ACCOUNTSTYLE,CHARGEFUNDINGACCOUNTID,LASTCREDITTRANSDTTM,LASTDEBITTRANSDTTM,"
            + "TEMPACCOUNTLIMIT,TEMPLIMEXPIRYDATE,PRODUCTCONTEXTCODE,BRANCHSORTCODE,UBACCTRANSCOUNTER,UBACCOUNTSTATUS,UBISARCHIVE,UBISDELETE,UBCUSTOMERCODE,UBACCRIGHTSINDREASON,UBACCRIGHTSINDCHANGEDT,UBACCRIGHTSINDCHANGEDBY,UBINDUSTRYCODE,UBUNACCRUEDAMOUNT,UBSIGNIFICANTEXCESSAMOUNT,UBNOTICEFREEWITHDRAWALAMOUNT,UBFABAPPLICABLE, UBCOOLINGOFFENDDT)"
            + "VALUES('0100500000100','nostro','EUR','','NOSTRO','NOSTRO',84602.300000,98916.600000,0.000000,'2011-09-20',0.000000,0.000000,'N','2011-08-14',NULL,'2011-08-14 19:03:07.000',NULL,'2013-08-30','N',NULL,"
            + "'1970-01-01',NULL,NULL,'N','1970-01-01','1970-01-01','N',0.000000,0.000000,'1970-01-01','N','N',0,0,'000001','','','','','1970-01-01 05:30:00.000','1970-01-01 00:00:00.000','2011-08-14','2011-08-14',NULL,NULL,NULL,NULL,"
            + "0,0,3,'1970-01-01',0.000000,'2011-08-14 00:00:00.000','2011-08-14 00:00:00.000','2011-08-14 00:00:00.000',1,NULL,NULL,'2013-08-30 12:40:46.504','2013-08-30 08:55:35.000',0.000000,'1970-01-01 00:00:00.000',"
            + "'01005InternalEUR',NULL,3,'002','N','N','000001',NULL,'1970-01-01',NULL,NULL,0,0,0,'N', '1970-01-01')";

    private static final String INSERT_CUSTOMER = "INSERT INTO CUSTOMER ( "
            + "CUSTOMERCODE,CUSTOMERTYPE,UBCUSTOMERSUBTYPE,SHORTNAME,PREFERREDLANGUAGE,UBKYCSTATUS,UBTAXPAYERIND,UBRELATIONSHIPMGRID,CUSTOMERSTATUS,UBBANKRELATIONSHIPSTATUS,UBSTATUSCHANGEDT,UBISARCHIVE,UBISDELETE,VERSIONNUM,"
            + "ALPHACODE,BRANCHSORTCODE,REPORTINGCURRENCY,CUSTSTMTPROFILEID,UBCREATEDTTM,STATEMENTCHANNEL,GROUPID,UBSTRATEGICGROUPING,BUSINESSUNIT,CUSTSEGMENTID,CUSTOMERCLASSIFICATION,UBREGULATORYDEF,CREDITGRADE,COUNTRYRISKRATING,CREDITRISKWEIGHT,"
            + "UBCREDITGRADEEXPDDT,UBWATCHLISTSTATUS,UBKYCEXPIRYDT,BANKRUPTINDICATOR,UBAUTHSUPERVISORID,UBLASTAUTHDTTM,UBAUTHSTATUS,FEEWAIVERINDICATOR,BUNDLEPRICINGAPPLICABLE,CHARGEFUNDINGACCOUNTID,TAXNUMBER,UBWITHHOLDINGTAXIND,UBBLOCKEDINDICATOR,"
            + "UBBLOCKEDREASON,UBCUSTSTATUSREASON,UBREJECTIONDT,UBDLNSTATUS,UBDLNLOANSTATUS,UBDLNPRFATTACHDT,UBTAXEXEMPTREASON,UBISCONSOLIDATESTMT)"
            + "VALUES('PER001','1062','100',  '001 P kumar','en',NULL,'N','retail','001',NULL,NULL,'N','N',0,'001 P kumar',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','0',NULL,"
            + "'Y','N','N',NULL,'0123','Y','N',NULL,NULL,NULL,NULL,NULL,NULL,'BLAH BLAH','N')";

    private static final String INSERT_CUSTOMER_NOSTRO = "INSERT INTO CUSTOMER ( "
            + "CUSTOMERCODE,CUSTOMERTYPE,UBCUSTOMERSUBTYPE,SHORTNAME,PREFERREDLANGUAGE,UBKYCSTATUS,UBTAXPAYERIND,UBRELATIONSHIPMGRID,CUSTOMERSTATUS,UBBANKRELATIONSHIPSTATUS,UBSTATUSCHANGEDT,UBISARCHIVE,UBISDELETE,VERSIONNUM,"
            + "ALPHACODE,BRANCHSORTCODE,REPORTINGCURRENCY,CUSTSTMTPROFILEID,UBCREATEDTTM,STATEMENTCHANNEL,GROUPID,UBSTRATEGICGROUPING,BUSINESSUNIT,CUSTSEGMENTID,CUSTOMERCLASSIFICATION,UBREGULATORYDEF,CREDITGRADE,COUNTRYRISKRATING,CREDITRISKWEIGHT,"
            + "UBCREDITGRADEEXPDDT,UBWATCHLISTSTATUS,UBKYCEXPIRYDT,BANKRUPTINDICATOR,UBAUTHSUPERVISORID,UBLASTAUTHDTTM,UBAUTHSTATUS,FEEWAIVERINDICATOR,BUNDLEPRICINGAPPLICABLE,CHARGEFUNDINGACCOUNTID,TAXNUMBER,UBWITHHOLDINGTAXIND,UBBLOCKEDINDICATOR,"
            + "UBBLOCKEDREASON,UBCUSTSTATUSREASON,UBREJECTIONDT,UBDLNSTATUS,UBDLNLOANSTATUS,UBDLNPRFATTACHDT,UBTAXEXEMPTREASON,UBISCONSOLIDATESTMT)"
            + "VALUES('000001','I','I',  'Internal','en_GB',NULL,'N','retail','001',NULL,NULL,'N','N',0,'Internal',NULL,'EUR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','0',NULL,"
            + "'Y','N','N',NULL,'0123','N','N',NULL,NULL,NULL,NULL,NULL,NULL,'BLAH BLAH','N')";

    private static final String INSERT_PRODUCTINHERITANCE = "INSERT INTO PRODUCTINHERITANCE ( "
            + "PRODUCTCONTEXTCODE,PRODUCTDESCRIPTION,ACC_DEFAULTDESCRIPTION,PRODUCT_NUMERICCODE,PRODUCT_ACC_PRODUCTID,ACC_ISOCURRENCYCODE,BSHEET_CRNOMINALCODE,BSHEET_DRNOMINALCODE,DRINT_FREQUENCYPERIODCODEDR,CRINT_FREQUENCYPERIODCODECR,DRINT_APPLICATIONMONTHDR,"
            + "CRINT_APPLICATIONMONTHCR,DRINT_APPLICATIONDAYDR,CRINT_APPLICATIONDAYCR,HAS_STM,ACC_FEEWAIVEINDICATOR,ACC_PASSBOOKINDICATOR,ACC_MINOPENINGBALANCEAMOUNT,ACC_PEROUTERPROFILEID,HAS_ACCNOTE,HAS_PSNAME,PSNAME_PSEUDONAME,HAS_BSHEET,"
            + "HAS_CHDEP,HAS_CHEQS,CHEQS_BANKCHEQUE,HAS_CCARD,CCARD_MINAMOUNTPERCENTAGE,CCARD_NUMBEROFDAYSTOPAY,CCARD_CCDESCRIPTION,HAS_CRINTEREST,CRINT_CREDITINTERESTRATE,CRINT_COSTCENTRE,CRINT_INTERESTBASEDAYSCR,CRINT_CREDITBASECODE,CRINT_CREDITINTERESTMARGIN,CRINT_FREQUENCYPERIODUNITCR,"
            + "CRINT_PAYAWAYCRACCOUNT,CRINT_INTERESTMETHODCR,CRINT_NOMINALCODE,HAS_DRINTEREST,DRINT_PENALTYINTEREST,DRINT_FREQUENCYPERIODUNITDR,DRINT_NOMINALCODE,DRINT_INTERESTMETHODDR,DRINT_PAYAWAYDRACCOUNT,DRINT_COSTCENTRE,DRINT_INTERESTBASEDAYSDR,"
            + "DRINT_DEBITINTERESTMARGIN,DRINT_DEBITBASECODE,DRINT_DEBITINTERESTRATE,HAS_FIX,HAS_LOAN,HAS_NOTICE,NOTICE_NOTICEPERIOD,HAS_OFFBAL,OFFBAL_OFFSETBALANCEMETHOD,HAS_OFFSET,HAS_PANDL,PANDL_RETAINEDEARNINGSACC,PANDL_COSTTYPE,PANDL_COSTCENTRECODE,"
            + "PANDL_NOMINALCODE,HAS_SFRV,HAS_TAX,ACC_TAXINDICATORDR,ACC_TAXINDICATORCR,HAS_TRS,TRS_PAYAWAYTRSACCOUNT,TRS_RELIEFPERCENTAGE,TRS_PAYGROSSREPAYMENT,TRS_ANNUALCEILING,HAS_LIM,LIM_LIMITINDICATOR,LIM_LIMITEXCESSACTION,LIM_DEBITLIMIT,LIM_CREDITLIMIT,"
            + "LIM_LIMITREF1,LIM_LIMITREF2,LIM_LIMITREF3,LIM_LIMITREF4,LIM_LIMITREF5,HAS_DRAWER,BSHEET_CRCOSTTYPE,BSHEET_DRCOSTTYPE,BSHEET_DRCOSTCENTRECODE,BSHEET_CRCOSTCENTRECODE,VERSIONNUM,HAS_BLOCKING,HAS_AVAILBAL,HAS_STATISTICS,HAS_MOVHIS,"
            + "CRINT_INTERESTRATECAP,CRINT_INTERESTRATECOLLAR,DRINT_INTERESTRATECAP,DRINT_INTERESTRATECOLLAR,DORMANCYMETHOD,DORMANCYPERIOD,NUMBEROFPERIODS,CREDITROUNDINGMETHOD,CREDITMULTIPLEOFCONSTANT,DEBITROUNDINGMETHOD,DEBITMULTIPLEOFCONSTANT,"
            + "ACCSTMTCFGID,UBDELINQUENCYPROFILEID,ISALLTRANSCODEALLOWED,UBINTSTMTPRFID,UBLASTCRINTMODDTTM,UBLASTDRINTMODDTTM,UBLIMITPERIOD,UBLIMITFREQ,UBLIMITREVIEWPERIOD,UBLIMITREVIEWFREQ,UBLASTMODIFIEDBY,UBLASTAPPROVEDBY,UBGENEXCPRPTFLAG,"
            + "UBPENALTYINTPRFID,UBPENALTYINTCAP,UBPENALINTCOLLAR,UBCOMMITMENTENFORCELEVEL,UBCOMMITMENTFLAG,UBACCOUNTSTATUS,UBISSUPERVISRAPPRREQD,UBCREDITRATEBASIS,UBDEBITRATEBASIS,UBINTACCRUALMETHODCR,UBINTACCRUALMETHODDR,UBCRAMTTENORRATEID,UBMINDEBITINTERESTAMT,"
            + "UBMINPENALTYINTAMT,UBMAXAMOUNTPERPRODUCT,UBINTERESTPERIODBASIS,UBINTERESTPAYOUT,UBMINTENORFREQUNIT,UBMINTENORFREQ,UBMAXTENORFREQUNIT,UBMAXTENORFREQ,UBSUBPRODUCTID,UBSEGMENTCLASSIFICATION,UBDOCCHECKLISTDEFID,UBISRECONCILABLE)"
            + "VALUES('01210DEFAULTEUR','Savings Account','Savings Account',1,'savings','EUR','2','3','F','F',6,6,0,0,'Y','N','Y',10.000000,'0000','Y','N','false','Y','Y','Y','N','N',0.000000,0,NULL,'Y',0E-8,'99999999',365,'0122',0.50000000,0,"
            + "NULL,0,'4','Y',0,0,'8',0,NULL,'99999999',360,0E-8,'0133',0E-8,'N','N','N',0,'Y',NULL,'N','N',NULL,NULL,NULL,NULL,'N','N',NULL,NULL,'N',NULL,0.000000,0,0.000000,'Y',0,0,0.000000,0.000000,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,"
            + "'99999999','99999999',0,'N','Y','N','N',20.000000,0.000000,20.000000,0.000000,'3','M',12,0,0,0,0,'1','00000001','Y','1','1970-01-01 05:30:00.000','1970-01-01 05:30:00.000',0,NULL,0,NULL,NULL,NULL,'Y','5',20.00000000,0E-8,"
            + "NULL,'N','002','N',1,1,0,0,NULL,0.000000,0.000000,0.000000,NULL,NULL,0,NULL,0,NULL,'01210','DEFAULT',NULL,'N')";

    private static final String INSERT_PRODUCTINHERITANCE1 = "INSERT INTO PRODUCTINHERITANCE ( "
            + "PRODUCTCONTEXTCODE,PRODUCTDESCRIPTION,ACC_DEFAULTDESCRIPTION,PRODUCT_NUMERICCODE,PRODUCT_ACC_PRODUCTID,ACC_ISOCURRENCYCODE,BSHEET_CRNOMINALCODE,BSHEET_DRNOMINALCODE,DRINT_FREQUENCYPERIODCODEDR,CRINT_FREQUENCYPERIODCODECR,DRINT_APPLICATIONMONTHDR,"
            + "CRINT_APPLICATIONMONTHCR,DRINT_APPLICATIONDAYDR,CRINT_APPLICATIONDAYCR,HAS_STM,ACC_FEEWAIVEINDICATOR,ACC_PASSBOOKINDICATOR,ACC_MINOPENINGBALANCEAMOUNT,ACC_PEROUTERPROFILEID,HAS_ACCNOTE,HAS_PSNAME,PSNAME_PSEUDONAME,HAS_BSHEET,"
            + "HAS_CHDEP,HAS_CHEQS,CHEQS_BANKCHEQUE,HAS_CCARD,CCARD_MINAMOUNTPERCENTAGE,CCARD_NUMBEROFDAYSTOPAY,CCARD_CCDESCRIPTION,HAS_CRINTEREST,CRINT_CREDITINTERESTRATE,CRINT_COSTCENTRE,CRINT_INTERESTBASEDAYSCR,CRINT_CREDITBASECODE,CRINT_CREDITINTERESTMARGIN,CRINT_FREQUENCYPERIODUNITCR,"
            + "CRINT_PAYAWAYCRACCOUNT,CRINT_INTERESTMETHODCR,CRINT_NOMINALCODE,HAS_DRINTEREST,DRINT_PENALTYINTEREST,DRINT_FREQUENCYPERIODUNITDR,DRINT_NOMINALCODE,DRINT_INTERESTMETHODDR,DRINT_PAYAWAYDRACCOUNT,DRINT_COSTCENTRE,DRINT_INTERESTBASEDAYSDR,"
            + "DRINT_DEBITINTERESTMARGIN,DRINT_DEBITBASECODE,DRINT_DEBITINTERESTRATE,HAS_FIX,HAS_LOAN,HAS_NOTICE,NOTICE_NOTICEPERIOD,HAS_OFFBAL,OFFBAL_OFFSETBALANCEMETHOD,HAS_OFFSET,HAS_PANDL,PANDL_RETAINEDEARNINGSACC,PANDL_COSTTYPE,PANDL_COSTCENTRECODE,"
            + "PANDL_NOMINALCODE,HAS_SFRV,HAS_TAX,ACC_TAXINDICATORDR,ACC_TAXINDICATORCR,HAS_TRS,TRS_PAYAWAYTRSACCOUNT,TRS_RELIEFPERCENTAGE,TRS_PAYGROSSREPAYMENT,TRS_ANNUALCEILING,HAS_LIM,LIM_LIMITINDICATOR,LIM_LIMITEXCESSACTION,LIM_DEBITLIMIT,LIM_CREDITLIMIT,"
            + "LIM_LIMITREF1,LIM_LIMITREF2,LIM_LIMITREF3,LIM_LIMITREF4,LIM_LIMITREF5,HAS_DRAWER,BSHEET_CRCOSTTYPE,BSHEET_DRCOSTTYPE,BSHEET_DRCOSTCENTRECODE,BSHEET_CRCOSTCENTRECODE,VERSIONNUM,HAS_BLOCKING,HAS_AVAILBAL,HAS_STATISTICS,HAS_MOVHIS,"
            + "CRINT_INTERESTRATECAP,CRINT_INTERESTRATECOLLAR,DRINT_INTERESTRATECAP,DRINT_INTERESTRATECOLLAR,DORMANCYMETHOD,DORMANCYPERIOD,NUMBEROFPERIODS,CREDITROUNDINGMETHOD,CREDITMULTIPLEOFCONSTANT,DEBITROUNDINGMETHOD,DEBITMULTIPLEOFCONSTANT,"
            + "ACCSTMTCFGID,UBDELINQUENCYPROFILEID,ISALLTRANSCODEALLOWED,UBINTSTMTPRFID,UBLASTCRINTMODDTTM,UBLASTDRINTMODDTTM,UBLIMITPERIOD,UBLIMITFREQ,UBLIMITREVIEWPERIOD,UBLIMITREVIEWFREQ,UBLASTMODIFIEDBY,UBLASTAPPROVEDBY,UBGENEXCPRPTFLAG,"
            + "UBPENALTYINTPRFID,UBPENALTYINTCAP,UBPENALINTCOLLAR,UBCOMMITMENTENFORCELEVEL,UBCOMMITMENTFLAG,UBACCOUNTSTATUS,UBISSUPERVISRAPPRREQD,UBCREDITRATEBASIS,UBDEBITRATEBASIS,UBINTACCRUALMETHODCR,UBINTACCRUALMETHODDR,UBCRAMTTENORRATEID,UBMINDEBITINTERESTAMT,"
            + "UBMINPENALTYINTAMT,UBMAXAMOUNTPERPRODUCT,UBINTERESTPERIODBASIS,UBINTERESTPAYOUT,UBMINTENORFREQUNIT,UBMINTENORFREQ,UBMAXTENORFREQUNIT,UBMAXTENORFREQ,UBSUBPRODUCTID,UBSEGMENTCLASSIFICATION,UBDOCCHECKLISTDEFID,UBISRECONCILABLE)"
            + "VALUES('01005InternalEUR','NOSTRO','NOSTRO',1,'nostro','EUR','2','3',NULL,NULL,0,0,0,0,'Y','N','N', 0.000000,'0000','N','Y','false','Y','N','N','N','N',0.000000,0,NULL,'N',0E-8,NULL,0,NULL,0E-8,0,"
            + "NULL,0,NULL,'N',0,0,NULL,0,NULL,NULL,0,0E-8,NULL,0E-8,'N','N','N',0,'N',NULL,'N','N',NULL,NULL,NULL,NULL,'N','N',NULL,NULL,'N',NULL,0.000000,0,0.000000,'Y',0,0,0.000000,0.000000,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,"
            + "NULL,NULL,0,'N','N','N','N',99.000000,0.000000,99.000000,0.000000,NULL,NULL,0,0,0,0,0,'1',NULL,'Y',NULL,'1970-01-01 05:30:00.000','1970-01-01 05:30:00.000',0,NULL,0,NULL,NULL,NULL,'Y',NULL,0.000000,0E-8,"
            + "NULL,'N','002','N',0,0,0,0,NULL,0.000000,0.000000,0.000000,NULL,NULL,0,NULL,0,NULL,'01005',NULL,NULL,'N')";

    private static final String INSERT_SWTCUSTOMERDETAIL = "INSERT INTO SWTCUSTOMERDETAIL ( "
            + "CUSTOMERCODE,BICCODE,ISFINANCIALINSTITUTE,ALTERNATEBICCODE,ALTERNATEACCOUNTNUMBER,DRACCOUNTNUMBER,CRACCOUNTNUMBER,ADVICEDAYS,FXCONTRACTPRINTIND,PAYMSGREQUIRED,STATEMENTMSGREQUIRED,TRANSSTMTFLAG,FXDEALCONFIRMREQUIRED,DEPOSITLOANCONFIRMREQUIRED,"
            + "CALLDEPOSITLOANCONFIRMREQD,DRCONFIRMREQUIRED,CRCONFIRMREQUIRED,VERSIONNUM,COVERMSGFLAG,SWTACTIVE,SWTACCOUNTNO,ADVICEMSGREQUIRED,DELIVERYCHANNEL,UBISARCHIVE,UBISDELETE)"
            + "VALUES('000005','ABNAGB2FXXX','Y', NULL, NULL, '', '', 0, 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 0, 0, 'Y', NULL, 'Y', NULL, 'N', 'N' )";

    private static final String INSERT_SWTCUSTOMERDETAIL1 = "INSERT INTO SWTCUSTOMERDETAIL ( "
            + "CUSTOMERCODE, BICCODE, ISFINANCIALINSTITUTE, ALTERNATEBICCODE, ALTERNATEACCOUNTNUMBER, DRACCOUNTNUMBER, CRACCOUNTNUMBER, ADVICEDAYS, FXCONTRACTPRINTIND, PAYMSGREQUIRED, STATEMENTMSGREQUIRED, TRANSSTMTFLAG, FXDEALCONFIRMREQUIRED, DEPOSITLOANCONFIRMREQUIRED, CALLDEPOSITLOANCONFIRMREQD, DRCONFIRMREQUIRED, CRCONFIRMREQUIRED, VERSIONNUM, COVERMSGFLAG, SWTACTIVE, SWTACCOUNTNO, ADVICEMSGREQUIRED, DELIVERYCHANNEL, UBISARCHIVE, UBISDELETE)"
            + "VALUES('PER001', 'ABNANL2AXXX', 'Y', NULL, NULL, '', '', 0, 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 0, 0, 'Y', NULL, 'Y', NULL, 'N', 'N' )";

    private static final String INSERT_SWTCUSTOMERDETAIL2 = "INSERT INTO SWTCUSTOMERDETAIL ( "
            + "CUSTOMERCODE, BICCODE, ISFINANCIALINSTITUTE, ALTERNATEBICCODE, ALTERNATEACCOUNTNUMBER, DRACCOUNTNUMBER, CRACCOUNTNUMBER, ADVICEDAYS, FXCONTRACTPRINTIND, PAYMSGREQUIRED, STATEMENTMSGREQUIRED, TRANSSTMTFLAG, FXDEALCONFIRMREQUIRED, DEPOSITLOANCONFIRMREQUIRED, CALLDEPOSITLOANCONFIRMREQD, DRCONFIRMREQUIRED, CRCONFIRMREQUIRED, VERSIONNUM, COVERMSGFLAG, SWTACTIVE, SWTACCOUNTNO, ADVICEMSGREQUIRED, DELIVERYCHANNEL, UBISARCHIVE, UBISDELETE)"
            + "VALUES('000001', 'SBZAZAJJXXX', 'Y', NULL, NULL, 'NOSTRO', 'NOSTRO', 0, 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 0, 0, 'Y', NULL, 'Y', NULL, 'N', 'N' )";

    private static final String INSERT_EXCHANGERATES = "INSERT INTO EXCHANGERATES ( "
            + "CURRENCYRATEID, FROMCURRENCYCODE, TOCURRENCYCODE, EXCHANGERATETYPE, MULTIPLYDIVIDE, UPDATEDATE, TOLERANCE, RATE, LIMIT1, RATE2, LIMIT2, REFER2, RATE3, LIMIT3, REFER3, RATE4, LIMIT4, REFER4, RATE5, LIMIT5, REFER5, RATE6, LIMIT6, REFER6, VERSIONNUM, SPOTPERIODINDAYS)"
            + "VALUES('1', 'EUR', 'GBP', 'SPOT', 'M', '2013-06-17', 5.000000, 0.49314500, 999999999999999999.990000, 0E-8, 0.000000, 'N', 0E-8, 0.000000, 'N', 0E-8, 0.000000, 'N', 0E-8, 0.000000, 'N', 0E-8, 0.000000, 'N', 0, 2)";

    private static final String INSERT_EXCHANGERATES1 = "INSERT INTO EXCHANGERATES( "
            + "CURRENCYRATEID, FROMCURRENCYCODE, TOCURRENCYCODE, EXCHANGERATETYPE, MULTIPLYDIVIDE, UPDATEDATE, TOLERANCE, RATE, LIMIT1, RATE2, LIMIT2, REFER2, RATE3, LIMIT3, REFER3, RATE4, LIMIT4, REFER4, RATE5, LIMIT5, REFER5, RATE6, LIMIT6, REFER6, VERSIONNUM, SPOTPERIODINDAYS)"
            + "VALUES('3', 'GBP', 'EUR', 'SPOT', 'M', '2013-06-17', 5.000000, 2.02780000, 999999999999999999.990000, 0E-8, 0.000000, 'N', 0E-8, 0.000000, 'N', 0E-8, 0.000000, 'N', 0E-8, 0.000000, 'N', 0E-8, 0.000000, 'N', 0, 2 )";

    private static final String INSERT_PSEUDONYM = "INSERT INTO PSEUDONYM("
            + "PSEUDONYMCODE, DESCRIPTION, VERSIONNUM, FINDERALTERNATIVE1, FINDERALTERNATIVE2, FINDERALTERNATIVE3, SUBPRODUCTIDENTIFIER, REFERONAUTOGEN )"
            + "VALUES( 'SPOTPOS', 'Spot Position Account', 0, '-1', '-1', '-1', '700', 'N' )";

    private static final String INSERT_PSEUDONYM1 = "INSERT INTO PSEUDONYM( "
            + "PSEUDONYMCODE, DESCRIPTION, VERSIONNUM, FINDERALTERNATIVE1, FINDERALTERNATIVE2, FINDERALTERNATIVE3, SUBPRODUCTIDENTIFIER, REFERONAUTOGEN )"
            + "VALUES( 'CURRPOS', 'Currency Position Account', 0, '-1', '-1', '-1', '700', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES('572befaa1f4a1175', 'BCASH', '0100100000100', 'BRANCH', '99999999', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP1 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572c15e42013ffff', 'BCASH', '0300100000100', 'BRANCH', '99999999', 'GBP', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP2 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572c41c720deffff', 'BCASH', '0500100000100', 'BRANCH', '99999999', 'JPY', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP3 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572c680f21a702c6', 'BCASH', '0100100000100', 'CURRENCY', 'EUR', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP4 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572c8f0f2270ffff', 'BCASH', '0300100000100', 'CURRENCY', 'GBP', 'GBP', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP5 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572cb64c2339ffff', 'BCASH', '0500100000100', 'CURRENCY', 'JPY', 'JPY', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP6 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572cdcfe24022056', 'CURRPOS', '0170000000100', 'CURRENCY', 'EUR', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP7 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572d041924cb0959', 'CURRPOS', '0370000000100', 'CURRENCY', 'GBP', 'GBP', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP8 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572d2b412594ffff', 'CURRPOS', '0570000000100', 'CURRENCY', 'JPY', 'JPY', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP9 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572d516f265b0293', 'CURRPOS', '0170000000100', 'BRANCH', '99999999', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP10 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572d776d0014ffff', 'CURRPOS', '0370000000100', 'BRANCH', '99999999', 'GBP', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP11 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572da05a00dfffff', 'CURRPOS', '0570000000100', 'BRANCH', '99999999', 'JPY', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP12 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572dc7d901a8ffff', 'SPOTPOS', '0170000000100', 'BRANCH', '99999999', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP13 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572decdd026f0339', 'SPOTPOS', '0370000000100', 'BRANCH', '99999999', 'GBP', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP14 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572e19aa033c2482', 'SPOTPOS', '0570000000100', 'BRANCH', '99999999', 'JPY', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP15 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572e405f0405ffff', 'SPOTPOS', '0170000000100', 'CURRENCY', 'EUR', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP16 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572e699b04ceffff', 'SPOTPOS', '0370000000100', 'CURRENCY', 'GBP', 'GBP', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP17 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572e90340597ffff', 'SPOTPOS', '0570000000100', 'CURRENCY', 'JPY', 'JPY', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP18 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572eb94f0660ffff', 'BSUSP', '0100100000100', 'BRANCH', '99999999', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP19 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '572ee1a2072b1eb7', 'BSUSP', '0100100000100', 'CURRENCY', 'EUR', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP20 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE)"
            + "VALUES( '9e017c2c1813ffff', 'NOSTRO', '0100500000100', 'BRANCH', '99999999', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP21 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( '9e01db4218ca14fb', 'NOSTRO', '0100500000100', 'CURRENCY', 'EUR', 'EUR', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP22 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID, PSEUDONAME, ACCOUNTID, SORTCONTEXT, SORTCONTEXTVALUE, ISOCURRENCYCODE, VERSIONNUM, ISDELETED, ISPROTECTED, UBISARCHIVE )"
            + "VALUES( 'b7f1a07e08d525f9', 'NOSTRO', '0300500000100', 'BRANCH', '99999999', 'GBP', 0, 'N', 'N', 'N' )";

    private static final String INSERT_PSEUDONYMACCMAP23 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID,   PSEUDONAME,   ACCOUNTID,   SORTCONTEXT,   SORTCONTEXTVALUE,   ISOCURRENCYCODE,   VERSIONNUM,   ISDELETED,   ISPROTECTED,   UBISARCHIVE)"
            + "VALUES(  'b7f246b60a9802cf',   'NOSTRO',   '0300500000100',   'CURRENCY',   'GBP',   'GBP',   0,   'N',   'N',   'N' )";

    private static final String INSERT_PSEUDONYMACCMAP24 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID,   PSEUDONAME,   ACCOUNTID,   SORTCONTEXT,   SORTCONTEXTVALUE,   ISOCURRENCYCODE,   VERSIONNUM,   ISDELETED,   ISPROTECTED,   UBISARCHIVE)"
            + "VALUES('9dgdf943fddfdfv999',  'POSITION_SPOT',  '0100500000100',  'BRANCH',  '99999999',  'EUR',  0,  'N',  'N',  'N')";

    private static final String INSERT_PSEUDONYMACCMAP25 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID,   PSEUDONAME,   ACCOUNTID,   SORTCONTEXT,   SORTCONTEXTVALUE,   ISOCURRENCYCODE,   VERSIONNUM,   ISDELETED,   ISPROTECTED,   UBISARCHIVE)"
            + "VALUES('9999999999999',  'POSITION_SPOT',  '0100500000100',  'CURRENCY',  '99999999',  'EUR',  0,  'N',  'N',  'N')";
    private static final String INSERT_PSEUDONYMACCMAP26 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID,   PSEUDONAME,   ACCOUNTID,   SORTCONTEXT,   SORTCONTEXTVALUE,   ISOCURRENCYCODE,   VERSIONNUM,   ISDELETED,   ISPROTECTED,   UBISARCHIVE)"
            + "VALUES('9dgdf943fd999dfdfv111',  'POSITION_SPOT',  '0100500000100',  'CURRENCY',  '',  'EUR',  0,  'N',  'N',  'N')";
    private static final String INSERT_PSEUDONYMACCMAP27 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID,   PSEUDONAME,   ACCOUNTID,   SORTCONTEXT,   SORTCONTEXTVALUE,   ISOCURRENCYCODE,   VERSIONNUM,   ISDELETED,   ISPROTECTED,   UBISARCHIVE)"
            + "VALUES('9dgdf943fddfdfv111111',  'NOSTRO',  '0100500000100',  'CURRENCY',  '',  'EUR',  0,  'N',  'N',  'N')";
    private static final String INSERT_PSEUDONYMACCMAP28 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID,   PSEUDONAME,   ACCOUNTID,   SORTCONTEXT,   SORTCONTEXTVALUE,   ISOCURRENCYCODE,   VERSIONNUM,   ISDELETED,   ISPROTECTED,   UBISARCHIVE)"
            + "VALUES('9dgdf9443111111',  'CURRENCY',  '0100500000100',  'ALTERNATE',  '',  'EUR',  0,  'N',  'N',  'N')";
    private static final String INSERT_PSEUDONYMACCMAP29 = "INSERT INTO PSEUDONYMACCOUNTMAP( "
            + "ID,   PSEUDONAME,   ACCOUNTID,   SORTCONTEXT,   SORTCONTEXTVALUE,   ISOCURRENCYCODE,   VERSIONNUM,   ISDELETED,   ISPROTECTED,   UBISARCHIVE)"
            + "VALUES('9dgdf9443111122',  '0100500000100',  '0100500000100',  'ALTERNATE',  '',  'EUR',  0,  'N',  'N',  'N')";

    private static final String INSERT_DEBITINTEREST = "INSERT INTO DEBITINTEREST( "
            + "DEBITINTERESTCODE, ACCOUNTID, DEBITBASECODE, DEBITACCDINTEREST, LASTDEBITRATECHANGEDATE, DEBITINTERESTMARGIN, PREVIOUSACCDRINTEREST, DEBITINTERESTRATE, LASTINTERESTAPPLIEDDR, LASTINTERESTAPPLICATIONDATE, INTERESTBASEDAYSDR, INTERESTMETHODDR, NOMINALDISCOUNTEDPRINCIPALDR, FREQUENCYPERIODCODEDR, FREQUENCYPERIODUNITDR, APPLICATIONDAYDR, APPLICATIONMONTHDR, NOMINALCODE, COSTCENTRE, PAYAWAYDRACCOUNT, ISOCURRENCYCODE, PENALTYINTEREST, LASTPENALTYBALANCE, LASTPENALTYACCRUAL, ORIGINALNOMINALCODE, VERSIONNUM, PREVIOUSCASHBALANCE, CALCULATEDINTERESTRATE, INTERESTRATECAP, INTERESTRATECOLLAR, UBLASTDRINTRTMODDTTM, UBINTRATECHGTXNCD, UBINTRATECHGTXNCDDESC, UBLASTMODIFIEDBY,"
            + " UBLASTAPPROVEDBY, UBINTRATECHGEFFECTIVEFLAG, UBAPRFORMULAID, UBAPR, UBPRODUCTTYPE, UBISARCHIVE, UBISDELETE, UBRATEBASIS, UBINTACCRUALMETHOD, UBBALTYPEINTCAL, UBNEXTINTERESTAPPLICATIONDTTM, UBISOTHERBANKFUNDINGACC )"
            + "VALUES ( '11', '01210PER00101', NULL, 0.000000, '2011-08-14 00:00:00.000', 0E-8, 0.000000, 0E-8, 0.000000, '1970-01-01 11:00:00.000', 360, 0, 0.000000, 'F', 0, 0, 6, '8', '99999999', NULL, 'EUR', 0, 0.000000, '1970-01-01', NULL, 18, 0.000000, 0.000000, 20.000000, 0.000000, '2011-08-14 18:48:07.803',"
            + " 'IRC', 'Fixed Narrative:Rate Change (Debit or Credit)', 'retail', NULL, NULL, NULL, 0E-8, '2', 'N', 'N', 1, 0, NULL, '1970-01-01 11:00:00.000', 'N' )";

    private static final String INSERT_CREDITINTEREST = "INSERT INTO CREDITINTEREST( "
            + "CREDITINTERESTCODE, ACCOUNTID, CREDITBASECODE, CREDITINTERESTRATE, ACCDCRINTEREST, CREDITINTERESTMARGIN, LASTCREDITRATECHANGEDATE, PREVIOUSACCCRINTEREST, LASTINTERESTAPPLIEDCR, LASTINTERESTAPPLICATIONDATE, INTERESTBASEDAYSCR, INTERESTMETHODCR, NOMINALDISCOUNTEDPRINCIPALCR, FREQUENCYPERIODCODECR, FREQUENCYPERIODUNITCR, APPLICATIONDAYCR, APPLICATIONMONTHCR, NOMINALCODE, COSTCENTRE, PAYAWAYCRACCOUNT, ISOCURRENCYCODE, VERSIONNUM, CALCULATEDINTERESTRATE, INTERESTRATECAP, INTERESTRATECOLLAR, WHTAPPLICABLE, WHTCALCMETHOD, YTDINTEREST, UBISWHTTHRESHCROSSED, UBLASTCRINTRTMODDTTM, UBINTRATECHGTXNCD, UBINTRATECHGTXNCDDESC, UBLASTMODIFIEDBY, UBLASTAPPROVEDBY,"
            + " UBISARCHIVE, UBISDELETE, UBRATEBASIS, UBINTACCRUALMETHOD, UBMINBALLASTINTACCRDT, UBAMTTENORRATEID, UBNEXTINTERESTAPPLICATIONDTTM, UBISOTHERBANKPAYAWAYACC )"
            + "VALUES( '11', '01210PER00101', NULL, 0E-8, 0.000000, 0E-8, '2011-08-14 00:00:00.000', 0.000000, 157.900000, '1970-01-01 05:30:00.000', 365, 0, 0.000000, 'F', 0, 0, 6, '4', '99999999', NULL, 'EUR', 28, 0.000000, 20.000000, 0.000000, 'N', NULL, 157.900000, 'N', '2011-08-14 18:48:07.803', 'IRC',"
            + " 'Fixed Narrative:Rate Change (Debit or Credit)', 'retail', NULL, 'N', 'N', 1, 0, '2011-08-14', NULL, '1970-01-01 05:30:00.000', 'N' )";

    private static final String INSERT_PENALTYINTEVENTS = "INSERT INTO UBTB_PENALTYINTEVENTS( "
            + "UBPIEVENTIDPK, UBACCOUNTID, UBPENALINTEVTTYPE, UBRATETYPE, UBPENALINTRATE, UBLASTPIRATEMODDTTM, UBPENALINTBASECODE, UBPENALINTMARGIN, UBEFFECTIVEDTTM, UBLASTPIACCRUEDDR, UBLASTPIACCRUALDTTM, UBISARREARSFLAG, UBARREARSAMT, UBACCRUNOMIALCD, UBNONACCRUNOMIALCD, VERSIONNUM, UBPENADJUSTAMT, UBACCRDAYS, UBPENLPAIDAMT, UBMODIFIEDBY, UBMODIFIEDDTTM, UBAPPROVEDBY, UBAPPROVEDDTTM )"
            + "VALUES( '9e0f1f190724ffff', '01210PER00101', 'T', 'FIXEDRATE', 10.00000000, '2011-08-14 19:27:08.132', NULL, 0E-8, '2011-08-14 19:27:02.796', 0.000000, '2011-09-20 12:40:46.240', 'N', 10.000000, '2', '3', 54, 0.000000, 0, 0.000000, 'system', '2011-08-14 19:27:08.231', NULL, '1970-01-01 05:30:00.000' )";

    private static final String INSERT_PENALTYINTEVENTS1 = "INSERT INTO UBTB_PENALTYINTEVENTS( "
            + "UBPIEVENTIDPK, UBACCOUNTID, UBPENALINTEVTTYPE, UBRATETYPE, UBPENALINTRATE, UBLASTPIRATEMODDTTM, UBPENALINTBASECODE, UBPENALINTMARGIN, UBEFFECTIVEDTTM, UBLASTPIACCRUEDDR, UBLASTPIACCRUALDTTM, UBISARREARSFLAG, UBARREARSAMT, UBACCRUNOMIALCD, UBNONACCRUNOMIALCD, VERSIONNUM, UBPENADJUSTAMT, UBACCRDAYS, UBPENLPAIDAMT, UBMODIFIEDBY, UBMODIFIEDDTTM, UBAPPROVEDBY, UBAPPROVEDDTTM )"
            + "VALUES( '9e0f202a0767244f', '01210PER00101', 'U', 'FIXEDRATE', 10.00000000, '2011-08-14 19:27:08.429', NULL, 0E-8, '2011-08-14 19:27:02.796', 0.000000, '2011-09-20 12:40:46.240', 'N', 10.000000, '2', '3', 54, 0.000000, 0, 0.000000, 'system', '2011-08-14 19:27:08.482', NULL, '1970-01-01 05:30:00.000' )";

    private static final String INSERT_PENALTYINTFEATURE = "INSERT INTO UBTB_PENALTYINTFEATURE( "
            + "UBACCOUNTID, UBCURRENCY, UBCOSTCENTRE, UBPENALINTRATECAP, UBPENALINTRATECOLLAR, UBLASTAPPLNDTTM, UBNEXTAPPLNDTTM, UBPRODUCTTYPE, UBMETHODTYPE, UBINTBASEDAYS, UBGRACEDAYS, VERSIONNUM, UBISARCHIVE, UBISDELETE )"
            + "VALUES( '01210PER00101', 'EUR', '99999999', 20.00000000, 0E-8, '2011-08-14 19:27:08.048', '1970-01-01 11:00:00.000', '2', 'METHOD1', 360, 0, 2, 'N', 'N' )";

    private static final String INSERT_PENALTYINTPROFILE = "INSERT INTO UBTB_PENALTYINTPROFILE( "
            + "UBPENALINTPROFIDPK, UBPENALINTPROFDESC, UBPENALINTGRACEPERIOD, UBPENALINTMETHOD, UBISDELETED, VERSIONNUM, UBMODIFIEDBY, UBMODIFIEDDTTM, UBAPPROVEDBY, UBAPPROVEDDTTM )"
            + "VALUES ( '5', 'PenaltyConfigMovement1', 0, 'METHOD1', 'N', 0, 'publish', '2013-06-17 23:46:45.610', NULL, '1970-01-01 05:30:00.000' )";

    private static final String INSERT_PENALTYINTRATE = "INSERT INTO UBTB_PENALTYINTRATE( "
            + "UBPENALINTRATEIDPK, UBPENALINTRATEDESC, UBRATETYPE, UBPENALINTRATE, UBPENALINTBASECODE, UBPENALINTMARGIN, UBPENALINTDTTM, UBISDELETED, VERSIONNUM )"
            + "VALUES ( '1', NULL, 'FIXEDRATE', 22.50000000, NULL, 0E-8, '1970-01-01 05:30:00.000', 'N', 0 )";

    private static final String INSERT_PENALTYINTRATE1 = "INSERT INTO UBTB_PENALTYINTRATE( "
            + "UBPENALINTRATEIDPK, UBPENALINTRATEDESC, UBRATETYPE, UBPENALINTRATE, UBPENALINTBASECODE, UBPENALINTMARGIN, UBPENALINTDTTM, UBISDELETED, VERSIONNUM )"
            + "VALUES( '2', NULL, 'BASERATE', 0E-8, '0198', 10.00000000, '1970-01-01 05:30:00.000', 'N', 0 )";

    private static final String INSERT_PENALTYINTRATE2 = "INSERT INTO UBTB_PENALTYINTRATE( "
            + "UBPENALINTRATEIDPK, UBPENALINTRATEDESC, UBRATETYPE, UBPENALINTRATE, UBPENALINTBASECODE, UBPENALINTMARGIN, UBPENALINTDTTM, UBISDELETED, VERSIONNUM )"
            + "VALUES(  '4', NULL, 'BASERATE', 0E-8, '0198', 10.00000000, '1970-01-01 05:30:00.000', 'N', 0 )";

    private static final String INSERT_ACCOUNTSTATEMENTCONFIG = "INSERT INTO UBTB_ACCOUNTSTATEMENTCONFIG( "
            + "UBACCSTMTCFGPK, UBDESCRIPTION, UBADHOC, UBSTMTPRNTDAY, UBSTMTFREQUENCY, UBSTMTMONTH, UBSTMTDAY, UBPAGEFULLALLOWED, UBTRANSACTIONSPERPAGE, UBSTMTALLOWEDFORDORMANT, UBSUPPRESSREVERSAL, UBMAILINGINSTRUCTIONS, UBTEMPLATEID, VERSIONNUM )"
            + "VALUES ( '1', 'Account Statement1', 1, '6017', 'M', 1, 1, 0, 10, 'Y', 'N', '1', '001', 0 )";

    private static final String INSERT_ACCOUNTSTATEMENTCONFIG1 = "INSERT INTO UBTB_ACCOUNTSTATEMENTCONFIG( "
            + "UBACCSTMTCFGPK, UBDESCRIPTION, UBADHOC, UBSTMTPRNTDAY, UBSTMTFREQUENCY, UBSTMTMONTH, UBSTMTDAY, UBPAGEFULLALLOWED, UBTRANSACTIONSPERPAGE, UBSTMTALLOWEDFORDORMANT, UBSUPPRESSREVERSAL, UBMAILINGINSTRUCTIONS, UBTEMPLATEID, VERSIONNUM )"
            + "VALUES ( '2', 'Account Statement2', 1, '6017', 'M', 1, 3, 0, 10, 'Y', 'N', '1', '003', 0 )";

    private static final String INSERT_ACCOUNTSTATEMENT = "INSERT INTO ACCOUNTSTATEMENT( "
            + "STATEMENTID, ACCOUNTID, CURRENTPAGE, CURRENTSRNUMBER, PERIODIC, LASTSTMTNUMBER, LASTSTMTPAGENUMBER, LASTSTMTDATE, FREQUENCYPERIODUNIT, VERSIONNUM, NUMBEROFSTATMENT, STMTDATE, BROUGHTFWDBALANCE, GENERATESTMTFLAG, UBISARCHIVE, UBISDELETE, UBACCSTMTCFGID, UBTRANSACTIONSPERPAGE, UBADHOC, UBFREQUENCYPERIODCODE, UBSTMTDAY, UBSTMTMONTH, UBSTMTALLOWEDFORDORMANT, UBSUPPRESSREVERSAL, UBPAGEFULL, UBSTMTPRNTDAY, UBBFAMTNXTSTMT )"
            + "VALUES ( '18', '01210PER00101', 1, 9, 0, 0, 0, '1970-01-01 05:30:00.000', 0, 8, 0, '1970-01-01 05:30:00.000', 0.000000, 'N', 'N', 'N', '1', 10, 1, 'M', 1, 1, 'Y', 'N', 0, '6017', 0.000000 )";

    private static final String INSERT_ACCOUNTSTATEMENT1 = "INSERT INTO ACCOUNTSTATEMENT( "
            + "STATEMENTID, ACCOUNTID, CURRENTPAGE, CURRENTSRNUMBER, PERIODIC, LASTSTMTNUMBER, LASTSTMTPAGENUMBER, LASTSTMTDATE, FREQUENCYPERIODUNIT, VERSIONNUM, NUMBEROFSTATMENT, STMTDATE, BROUGHTFWDBALANCE, GENERATESTMTFLAG, UBISARCHIVE, UBISDELETE, UBACCSTMTCFGID, UBTRANSACTIONSPERPAGE, UBADHOC, UBFREQUENCYPERIODCODE, UBSTMTDAY, UBSTMTMONTH, UBSTMTALLOWEDFORDORMANT, UBSUPPRESSREVERSAL, UBPAGEFULL, UBSTMTPRNTDAY, UBBFAMTNXTSTMT )"
            + "VALUES ( '19', '0100500000100', 5, 14, 0, 0, 0, '1970-01-01 05:30:00.000', 0, 106, 0, '1970-01-01 05:30:00.000', 0.000000, 'N', 'N', 'N', '1', 10, 1, 'M', 1, 1, 'Y', 'N', 0, '6017', 0.000000 )";

    private static final String INSERT_DORMANCY = "INSERT INTO DORMANCYFEATURE( "
            + "DORMANCYFEATUREID, ACCOUNTID, DORMANCYSTATUS, LASTACTIVETRANSACTIONDATE, VERSIONNUM, UBISARCHIVE, UBISDELETE )"
            + "VALUES( '9deb67420e500dfe', '01210PER00101', 'N', '2011-09-07', 0, 'N', 'N' )";

    private static final String INSERT_SHADOWACC = "INSERT INTO SHADOWACCOUNT( "
            + "ACCOUNTID, SHADOWCLEAREDBALANCE, SHADOWBOOKEDBALANCE, SHADOWDEBITLIMIT, SHADOWCREDITLIMIT, SHADOWLASTCRINTAPPAMOUNT, SHADOWLASTDRINTAPPAMOUNT, SHADOWINTAPPDATEDR, SHADOWINTAPPDATECR, SHADOWLASTTRANSACTIONDATE, SHADOWACCRUEDINTERESTDEBIT, SHADOWACCRUEDINTERESTCREDIT, SHADOWLASTINTERESTACCRUALDATE, SHADOWLASTDRRATECHANGEDDATE, SHADOWLASTCRRATECHANGEDDATE, SHADOWCREDITINTERESTMARGIN, SHADOWDEBITINTERESTMARGIN, SHADOWCREDITINTERESTRATE, SHADOWDEBITINTERESTRATE, SHADOWDEBITBASECODE,"
            + " SHADOWCREDITBASECODE, BLOCKEDFUNDSAMOUNT, SHADOWLASTCRLIMITCHANGEDATE, SHADOWLASTDRLIMITCHANGEDATE, ISOCURRENCYCODE, VERSIONNUM, UBISARCHIVE, UBISDELETE )"
            + "VALUES ( '0100500000100', 84602.300000, 98916.600000, 0.000000, 0.000000, 0.000000, 0.000000, '1970-01-01', '1970-01-01', '2013-08-30', 0.000000, 0.000000, '2011-09-20',"
            + " '1970-01-01', '1970-01-01', 0.000000, 0.000000, 0.000000, 0.000000, NULL, NULL, 0.000000, '1970-01-01', '1970-01-01', 'EUR', 128, 'N', 'N' )";

    private static final String INSERT_SHADOWACC1 = "INSERT INTO SHADOWACCOUNT( "
            + "ACCOUNTID, SHADOWCLEAREDBALANCE, SHADOWBOOKEDBALANCE, SHADOWDEBITLIMIT, SHADOWCREDITLIMIT, SHADOWLASTCRINTAPPAMOUNT, SHADOWLASTDRINTAPPAMOUNT, SHADOWINTAPPDATEDR, SHADOWINTAPPDATECR, SHADOWLASTTRANSACTIONDATE, SHADOWACCRUEDINTERESTDEBIT, SHADOWACCRUEDINTERESTCREDIT, SHADOWLASTINTERESTACCRUALDATE, SHADOWLASTDRRATECHANGEDDATE, SHADOWLASTCRRATECHANGEDDATE, SHADOWCREDITINTERESTMARGIN, SHADOWDEBITINTERESTMARGIN, SHADOWCREDITINTERESTRATE, SHADOWDEBITINTERESTRATE, SHADOWDEBITBASECODE,"
            + " SHADOWCREDITBASECODE, BLOCKEDFUNDSAMOUNT, SHADOWLASTCRLIMITCHANGEDATE, SHADOWLASTDRLIMITCHANGEDATE, ISOCURRENCYCODE, VERSIONNUM, UBISARCHIVE, UBISDELETE )"
            + "VALUES( '01210PER00101', 2909.000000, 2909.000000, 0.000000, 0.000000, 0.000000, 0.000000, '1970-01-01', '1970-01-01', '2013-08-30', 0.000000, 0.000000, '2011-09-20', '1970-01-01',"
            + " '1970-01-01', 0.500000, 0.000000, 0.000000, 0.000000, '0133', '0122', 0.000000, '1970-01-01', '1970-01-01', 'EUR', 81, 'N', 'N' )";

    private static final String INSERT_BICCODES = "INSERT INTO BICCODES( "
            + "BICCODE, NAME, LOCATION, CITY, BKEAUTH, VERSIONNUM, ISDELETED )"
            + "VALUES ( 'SBSASAJJ999', 'Standard Bank', 'South Africa', 'Nelson Mandela Avenue', 'Y', 0, 'N' )";

    private static final String INSERT_BICCODES1 = "INSERT INTO BICCODES( "
            + "BICCODE, NAME, LOCATION, CITY, BKEAUTH, VERSIONNUM, ISDELETED )"
            + "VALUES ( 'SBSASAJJ900', 'Standard Bank', 'Maseru Branch', 'South Africa', 'Y', 0, 'N' )";

    private static final String INSERT_BICCODES2 = "INSERT INTO BICCODES( "
            + "BICCODE, NAME, LOCATION, CITY, BKEAUTH, VERSIONNUM, ISDELETED )"
            + "VALUES ( 'SBSASAJJ004', 'SBSA', 'Johannesburg', 'South Africa', 'Y', 0, 'N' )";

    private static final String INSERT_BICCODES3 = "INSERT INTO BICCODES( "
            + "BICCODE, NAME, LOCATION, CITY, BKEAUTH, VERSIONNUM, ISDELETED )"
            + "VALUES ( 'ABNANL2AXXX', 'ABN AMRO BANK', 'NETHERLANDS', 'NETHERLANDS', 'Y', 0, 'N' )";

    private static final String INSERT_BICCODES4 = "INSERT INTO BICCODES( "
            + "BICCODE, NAME, LOCATION, CITY, BKEAUTH, VERSIONNUM, ISDELETED )"
            + "VALUES ( 'ABNAGB2FXXX', 'ABN Amro Japan', 'Yokohama', 'Japan', 'Y', 0, 'N' )";

    private static final String INSERT_BICCODES5 = "INSERT INTO BICCODES( "
            + "BICCODE, NAME, LOCATION, CITY, BKEAUTH, VERSIONNUM, ISDELETED )"
            + "VALUES ( 'AXABDE31XXX', 'AXA Bank', 'Lyon', 'France', 'Y', 0, 'N' )";

    private static final String INSERT_BICCODES6 = "INSERT INTO BICCODES( "
            + "BICCODE, NAME, LOCATION, CITY, BKEAUTH, VERSIONNUM, ISDELETED )"
            + "VALUES( 'SBZAZAJJICM', 'SBSA', 'Durban', 'South Africa', 'Y', 0, 'N' )";

    private static final String INSERT_BICCODES7 = "INSERT INTO BICCODES( "
            + "BICCODE, NAME, LOCATION, CITY, BKEAUTH, VERSIONNUM, ISDELETED )"
            + "VALUES ( 'SBZAZAJJXXX', 'SBSA', 'Johannesburg', 'South Africa', 'Y', 0, 'N' )";

    private static final String INSERT_BICCODES8 = "INSERT INTO BICCODES( "
            + "BICCODE, NAME, LOCATION, CITY, BKEAUTH, VERSIONNUM, ISDELETED )"
            + "VALUES ( 'BARCSCSCXXX', 'Barclays Bank', 'London', 'United Kingdom', 'Y', 0, 'N' )";

    private static final String UPDATE_BRANCH = "UPDATE BFTB_BRANCH SET BFBICCODE = 'SBZAZAJJXXX' WHERE BFBRANCHSORTCODEPK = '99999999'";

    private static final String UPDATE_MODULECONFIG = "UPDATE CBTB_MODULECONFIGURATION SET CBPARAMVALUE = 'SPOTPOS' WHERE CBMODULECONFIGURATIONID = 'UBModuleConfig98'";

    private static final String UPDATE_BRANCH1 = "UPDATE BRANCH SET BICCODE = 'SBZAZAJJXXX' WHERE BRANCHSORTCODE = '99999999'";

    private static final String INSERT_SETTLINSTR = "INSERT INTO SETTLEMENTINSTRUCTIONS( "
            + "SETTLEMENTINSTRUCTIONSID, ISOCURRENCYCODE, CUSTOMERCODE, MESSAGETYPE, VERSIONNUM, UBINSTRUCTIONIDENTIFIER, UBMESSAGECHANNEL, UBDEBITACCOUNTID, UBEXCHANGERATETYPE, UBEXPIRYDTTM, UBINSTRUCTIONSTATUS, UBCHANNELPERMISSIONSID )"
            + "VALUES ( 'SWT0PER001EUR001', 'EUR', 'PER001', '103', 0, 'SWT0PER001EUR001', 'SWIFT', NULL, NULL, '9999-12-31 05:30:00.000', NULL, NULL )";

    private static final String INSERT_SETTLINSTR1 = "INSERT INTO SETTLEMENTINSTRUCTIONS ( "
            + "SETTLEMENTINSTRUCTIONSID, ISOCURRENCYCODE, CUSTOMERCODE, MESSAGETYPE, VERSIONNUM, UBINSTRUCTIONIDENTIFIER, UBMESSAGECHANNEL, UBDEBITACCOUNTID, UBEXCHANGERATETYPE, UBEXPIRYDTTM, UBINSTRUCTIONSTATUS, UBCHANNELPERMISSIONSID )"
            + "VALUES ( 'SWT0PER001EUR023', 'EUR', 'PER001', '320', 0, 'SWT0PER001EUR023', 'SWIFT', NULL, NULL, '9999-12-31 05:30:00.000', NULL, NULL )";

    private static final String INSERT_SETTLINSTRDETAIL = "INSERT INTO SETTLEMENTINSTRUCTIONSDETAIL( "
            + "DETAILID, SETTLEMENTINSTRUCTIONSID, MESSAGE_NUMBER, PAY_RECEIVE_FLAG, PAY_TO_CODE, PAY_TO_TEXT1, PAY_TO_TEXT2, PAY_TO_TEXT3, BENEFICIARY_CODE, BENEFICIARY_TEXT1, BENEFICIARY_TEXT2, BENEFICIARY_TEXT3, INTERMEDIARY_CODE, INTERMEDIARY_TEXT1, INTERMEDIARY_TEXT2, INTERMEDIARY_TEXT3, FOR_ACCOUNT_TEXT1, FOR_ACCOUNT_TEXT2, FOR_ACCOUNT_TEXT3, BANK_TO_BANK_INFO1, BANK_TO_BANK_INFO2, BANK_TO_BANK_INFO3, BANK_TO_BANK_INFO4,"
            + " BANK_TO_BANK_INFO5, BANK_TO_BANK_INFO6, PAY_DETAILS1, PAY_DETAILS2, PAY_DETAILS3, PAY_DETAILS4, CHARGECODE, BANK_OPERATION_CODE, BANK_ADDL_INSTRUCTION_CODE, BANK_INSTRUCTION_CODE, PARTYIDENTIFIER, PARTYADDRESSLINE1, PARTYADDRESSLINE2, PARTYADDRESSLINE3, PARTYADDRESSLINE4, VERSIONNUM, DEBITACCOUNTID, CREDITACCOUNTID, NARRATIVE, ORDERINGINSTITUTION, GENERATE103PLUSIND, ORDERINGCUSTOMERACCID, SENDER_TO_RECEIVER_INFO1, SENDER_TO_RECEIVER_INFO2,"
            + " SENDER_TO_RECEIVER_INFO3, SENDER_TO_RECEIVER_INFO4, SENDER_TO_RECEIVER_INFO5, SENDER_TO_RECEIVER_INFO6, ORDERINGINSTITUTE_ACCID, FOR_ACC_IDENTIFIERCODE, ORDERINGCUST_IDENTIFIERCODE, PAY_TO_PARTY_IDENTIFIER, INTERMEDIARY_PARTY_IDENTIFIER, BENEFICIARY_PARTY_IDENTIFIER, FOR_ACCOUNT_PARTY_IDENTIFIER, ORDERINGINSTITUTIONDTL1, ORDERINGINSTITUTIONDTL2, ORDERINGINSTITUTIONDTL3, ORDERINGINSTITUTIONDTL4, INTERMEDIARY_TEXT4, PAY_TO_TEXT4,"
            + " BENEFICIARY_TEXT4, FOR_ACCOUNT_TEXT4, TERMS_CONDITIONS_INFO1, TERMS_CONDITIONS_INFO2, TERMS_CONDITIONS_INFO3, TERMS_CONDITIONS_INFO4, TERMS_CONDITIONS_INFO5, TERMS_CONDITIONS_INFO6, UBSITYPE, UBCREATEDTTM, UBTXNTYPECODE, UBORDERINGCUSTIDENTIFIERTYPE, UBBENEFCUSTIDENTIFIERTYPE )"
            + "VALUES ( 'SWT0PER001EUR023', 'SWT0PER001EUR023', 1, 'P', NULL, NULL, NULL, NULL, 'BARCSCSCXXX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'SWIFT_ACC1', 'AXABDE31XXX', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SBZAZAJJICM', 'ABNAGB2FXXX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, "
            + "NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'D', '2011-08-22 00:33:31.484', NULL, NULL, NULL )";

    private static final String INSERT_SETTLINSTRDETAIL1 = "INSERT INTO SETTLEMENTINSTRUCTIONSDETAIL( "
            + "DETAILID, SETTLEMENTINSTRUCTIONSID, MESSAGE_NUMBER, PAY_RECEIVE_FLAG, PAY_TO_CODE, PAY_TO_TEXT1, PAY_TO_TEXT2, PAY_TO_TEXT3, BENEFICIARY_CODE, BENEFICIARY_TEXT1, BENEFICIARY_TEXT2, BENEFICIARY_TEXT3, INTERMEDIARY_CODE, INTERMEDIARY_TEXT1, INTERMEDIARY_TEXT2, INTERMEDIARY_TEXT3, FOR_ACCOUNT_TEXT1, FOR_ACCOUNT_TEXT2, FOR_ACCOUNT_TEXT3, BANK_TO_BANK_INFO1, BANK_TO_BANK_INFO2, BANK_TO_BANK_INFO3, BANK_TO_BANK_INFO4, BANK_TO_BANK_INFO5,"
            + " BANK_TO_BANK_INFO6, PAY_DETAILS1, PAY_DETAILS2, PAY_DETAILS3, PAY_DETAILS4, CHARGECODE, BANK_OPERATION_CODE, BANK_ADDL_INSTRUCTION_CODE, BANK_INSTRUCTION_CODE, PARTYIDENTIFIER, PARTYADDRESSLINE1, PARTYADDRESSLINE2, PARTYADDRESSLINE3, PARTYADDRESSLINE4, VERSIONNUM, DEBITACCOUNTID, CREDITACCOUNTID, NARRATIVE, ORDERINGINSTITUTION, GENERATE103PLUSIND, ORDERINGCUSTOMERACCID, SENDER_TO_RECEIVER_INFO1, SENDER_TO_RECEIVER_INFO2,"
            + " SENDER_TO_RECEIVER_INFO3, SENDER_TO_RECEIVER_INFO4, SENDER_TO_RECEIVER_INFO5, SENDER_TO_RECEIVER_INFO6, ORDERINGINSTITUTE_ACCID, FOR_ACC_IDENTIFIERCODE, ORDERINGCUST_IDENTIFIERCODE, PAY_TO_PARTY_IDENTIFIER, INTERMEDIARY_PARTY_IDENTIFIER, BENEFICIARY_PARTY_IDENTIFIER, FOR_ACCOUNT_PARTY_IDENTIFIER, ORDERINGINSTITUTIONDTL1, ORDERINGINSTITUTIONDTL2, ORDERINGINSTITUTIONDTL3, ORDERINGINSTITUTIONDTL4, INTERMEDIARY_TEXT4, PAY_TO_TEXT4,"
            + " BENEFICIARY_TEXT4, FOR_ACCOUNT_TEXT4, TERMS_CONDITIONS_INFO1, TERMS_CONDITIONS_INFO2, TERMS_CONDITIONS_INFO3, TERMS_CONDITIONS_INFO4, TERMS_CONDITIONS_INFO5, TERMS_CONDITIONS_INFO6, UBSITYPE, UBCREATEDTTM, UBTXNTYPECODE, UBORDERINGCUSTIDENTIFIERTYPE, UBBENEFCUSTIDENTIFIERTYPE )"
            + "VALUES ( 'SWT0PER001EUR030', 'SWT0PER001EUR001', 13, NULL, NULL, NULL, NULL, NULL, 'BARCSCSCXXX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SBSA', 'South Africa', 'Durban', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SHA', 'CRED', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, '103P_26T', 'AXABDE31XXX', 'Y', '/ININD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ABNAGB2FXXX', NULL, NULL, NULL, '/CLYDI', "
            + "NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'D', '2011-08-24 17:50:02.730', '/CCT/', 'I', 'I' )";

    private static final String UPDATEACCOUNT1 = "UPDATE ACCOUNT SET UBSUBSCRIPTIONUSEDAMT = 0, UBSUBSCRIPTIONAMT = 0, UBDORMANCYAPPLYEXCLUDERULE = 'N' WHERE ACCOUNTID = '0100500000100'";
    private static final String UPDATEACCOUNT2 = "UPDATE ACCOUNT SET UBSUBSCRIPTIONUSEDAMT = 0, UBSUBSCRIPTIONAMT = 0, UBDORMANCYAPPLYEXCLUDERULE = 'N' WHERE ACCOUNTID = '01210PER00101'";

    private static final String productUpdate1 = "UPDATE PRODUCTINHERITANCE SET UBISCUSTMARGINENABLED = 'N' WHERE PRODUCTCONTEXTCODE = '01210DEFAULTEUR'";
    private static final String productUpdate2 = "UPDATE PRODUCTINHERITANCE SET UBISCUSTMARGINENABLED = 'N' WHERE PRODUCTCONTEXTCODE = '01005InternalEUR'";

    private static final String SettmentDetail1 = "UPDATE  SETTLEMENTINSTRUCTIONSDETAIL SET UBISNONDELIVERABLE ='Y', UBISNDFOPEN ='Y', UBSETTLEMENTCCY='EUR', UBVALUATIONDATE='2011-01-01', UBSETTLEMENTRATESRC='ABC12/1010/ASDD' WHERE DETAILID='SWT0PER001EUR023'";
    private static final String SettmentDetail2 = "UPDATE  SETTLEMENTINSTRUCTIONSDETAIL SET UBISNONDELIVERABLE ='Y', UBISNDFOPEN ='Y', UBSETTLEMENTCCY='EUR', UBVALUATIONDATE='2011-01-01', UBSETTLEMENTRATESRC='ABC12/1010/ASDD' WHERE DETAILID='SWT0PER001EUR030'";

    @Override
    public void process(BankFusionEnvironment env) {

        PreparedStatement ps = null;
        Connection connection = null;

        try {

            connection = factory.getJDBCConnection();
            ps = connection.prepareStatement(INSERT_ACCOUNT);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_ACCOUNT1);
            ps.executeUpdate();
            ps.close();

            // account update
            ps = connection.prepareStatement(UPDATEACCOUNT1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(UPDATEACCOUNT2);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_CUSTOMER);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_CUSTOMER_NOSTRO);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PRODUCTINHERITANCE);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PRODUCTINHERITANCE1);
            ps.executeUpdate();
            ps.close();

            // update product

            ps = connection.prepareStatement(productUpdate1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(productUpdate2);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(SettmentDetail1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(SettmentDetail2);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_SWTCUSTOMERDETAIL);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_SWTCUSTOMERDETAIL1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_SWTCUSTOMERDETAIL2);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_EXCHANGERATES);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_EXCHANGERATES1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYM);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYM1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP2);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP3);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP4);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP5);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP6);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP7);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP8);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP9);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP10);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP11);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP12);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP13);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP14);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP15);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP16);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP17);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP18);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP19);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP20);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP21);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP22);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP23);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP24);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP25);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP26);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP27);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP28);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PSEUDONYMACCMAP29);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_DEBITINTEREST);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_CREDITINTEREST);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PENALTYINTEVENTS);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PENALTYINTEVENTS1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PENALTYINTFEATURE);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PENALTYINTPROFILE);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PENALTYINTRATE);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PENALTYINTRATE1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_PENALTYINTRATE2);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_ACCOUNTSTATEMENTCONFIG);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_ACCOUNTSTATEMENTCONFIG1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_ACCOUNTSTATEMENT);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_ACCOUNTSTATEMENT1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_DORMANCY);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_SHADOWACC);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_SHADOWACC1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_BICCODES);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_BICCODES1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_BICCODES2);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_BICCODES3);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_BICCODES4);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_BICCODES5);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_BICCODES6);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_BICCODES7);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_BICCODES8);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_SETTLINSTR);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_SETTLINSTR1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_SETTLINSTRDETAIL);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(INSERT_SETTLINSTRDETAIL1);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(UPDATE_BRANCH);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(UPDATE_MODULECONFIG);
            ps.executeUpdate();
            ps.close();

            ps = connection.prepareStatement(UPDATE_BRANCH1);
            ps.executeUpdate();

            factory.commitTransaction();

            factory.beginTransaction(); //

        }
        catch (SQLException sqlException) {
            logger.error("populate details()", sqlException);
            factory.rollbackTransaction(); //

            factory.beginTransaction(); //

            throw new BankFusionException(-1, sqlException.getLocalizedMessage());

        }
        finally {
            if (ps != null) {
                try {
                    ps.close();
                }
                catch (SQLException e) {
                    logger.error(ExceptionUtil.getExceptionAsString(e));
                }
            }
        }

    }
}