package com.finastra.api.atm.v1.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.validation.Valid;

import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Used as a standard error message structure that complies with RFC7807.
 */
@ApiModel(description = "Used as a standard error message structure that complies with RFC7807.")
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-26T12:19:00.869+05:30")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Error   {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("detail")
  private String detail = null;

  @JsonProperty("causes")
  @Valid
  private List<Causes> causes = null;

  public Error type(String type) {
    this.type = type;
    return this;
  }

  /**
   * A URI reference [RFC3986] that identifies the problem type.
   * @return type
  **/
  @ApiModelProperty(example = "https://api.finastra.com/validation-error", value = "A URI reference [RFC3986] that identifies the problem type.")


  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Error title(String title) {
    this.title = title;
    return this;
  }

  /**
   * A short human-readable summary of the problem type.
   * @return title
  **/
  @ApiModelProperty(example = "The request is invalid", value = "A short human-readable summary of the problem type.")


  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Error status(Integer status) {
    this.status = status;
    return this;
  }

  /**
   * The HTTP status code generated by the origin server for this          occurrence of the problem
   * @return status
  **/
  @ApiModelProperty(example = "400", value = "The HTTP status code generated by the origin server for this          occurrence of the problem")


  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Error detail(String detail) {
    this.detail = detail;
    return this;
  }

  /**
   * A short human-readable explanation specific to this occurrence of the problem
   * @return detail
  **/
  @ApiModelProperty(example = "The account does not exist", value = "A short human-readable explanation specific to this occurrence of the problem")


  public String getDetail() {
    return detail;
  }

  public void setDetail(String detail) {
    this.detail = detail;
  }

  public Error causes(List<Causes> causes) {
    this.causes = causes;
    return this;
  }

  public Error addCausesItem(Causes causesItem) {
    if (this.causes == null) {
      this.causes = new ArrayList<Causes>();
    }
    this.causes.add(causesItem);
    return this;
  }

  /**
   * An optional array of additional causes associated with the error
   * @return causes
  **/
  @ApiModelProperty(value = "An optional array of additional causes associated with the error")

  @Valid

  public List<Causes> getCauses() {
    return causes;
  }

  public void setCauses(List<Causes> causes) {
    this.causes = causes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.type, error.type) &&
        Objects.equals(this.title, error.title) &&
        Objects.equals(this.status, error.status) &&
        Objects.equals(this.detail, error.detail) &&
        Objects.equals(this.causes, error.causes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, title, status, detail, causes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    causes: ").append(toIndentedString(causes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

